import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { resolve } from 'path';

config({ path: resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!serviceRoleKey) {
    console.error('❌ SUPABASE_SERVICE_ROLE_KEY is missing from .env.local');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

const questions = [
    // ===== BIOLOGY - Genetics =====
    { id: 'bio-gen-q1', subject: 'Biology', topic: 'Genetics', difficulty: 'medium', stem: 'Which of the following is the primary function of DNA helicase during DNA replication?', options: ['A) To synthesize new DNA strands', 'B) To unwind and separate the double helix', 'C) To join Okazaki fragments', 'D) To add RNA primers', 'E) To proofread newly synthesized DNA'], correct_answer: 1, explanation: 'DNA helicase unwinds the double helix by breaking hydrogen bonds between base pairs, creating replication forks where new strands can be synthesized.', source: 'official-imat', year: 2023 },
    { id: 'bio-gen-q2', subject: 'Biology', topic: 'Genetics', difficulty: 'hard', stem: 'In a dihybrid cross between two AaBb individuals, what fraction of the offspring would be expected to show both dominant phenotypes?', options: ['A) 1/16', 'B) 3/16', 'C) 9/16', 'D) 3/4', 'E) 1/4'], correct_answer: 2, explanation: 'In a dihybrid cross (AaBb × AaBb), 9/16 of the offspring show both dominant phenotypes (A_B_), following the 9:3:3:1 ratio.', source: 'official-imat', year: 2024 },
    { id: 'bio-gen-q3', subject: 'Biology', topic: 'Genetics', difficulty: 'easy', stem: 'What is the complementary DNA strand for the sequence 5\'-ATCGG-3\'?', options: ['A) 3\'-TAGCC-5\'', 'B) 3\'-ATCGG-5\'', 'C) 5\'-TAGCC-3\'', 'D) 5\'-UAGCC-3\'', 'E) 3\'-UAGCC-5\''], correct_answer: 0, explanation: 'DNA base pairing follows A-T and C-G rules. The complement of ATCGG is TAGCC, running antiparallel (3\' to 5\').', source: 'locomotive-original', year: null },
    { id: 'bio-gen-q4', subject: 'Biology', topic: 'Genetics', difficulty: 'medium', stem: 'Which type of mutation involves the insertion or deletion of nucleotides that shifts the reading frame?', options: ['A) Point mutation', 'B) Silent mutation', 'C) Frameshift mutation', 'D) Missense mutation', 'E) Nonsense mutation'], correct_answer: 2, explanation: 'Frameshift mutations occur when insertions or deletions of nucleotides (not in multiples of 3) shift the reading frame, altering all downstream codons.', source: 'official-imat', year: 2022 },
    { id: 'bio-gen-q5', subject: 'Biology', topic: 'Genetics', difficulty: 'hard', stem: 'A woman who is a carrier for hemophilia (X-linked recessive) marries a normal man. What is the probability that their son will have hemophilia?', options: ['A) 0%', 'B) 25%', 'C) 50%', 'D) 75%', 'E) 100%'], correct_answer: 2, explanation: 'The carrier mother (XᴴXʰ) has a 50% chance of passing the hemophilia allele to each son. Sons who receive Xʰ will have hemophilia since they only have one X chromosome.', source: 'italian-medical', year: null },
    { id: 'bio-gen-q6', subject: 'Biology', topic: 'Genetics', difficulty: 'medium', stem: 'Which enzyme is responsible for joining Okazaki fragments during DNA replication?', options: ['A) DNA polymerase I', 'B) DNA polymerase III', 'C) DNA ligase', 'D) Primase', 'E) Topoisomerase'], correct_answer: 2, explanation: 'DNA ligase joins Okazaki fragments by forming phosphodiester bonds between the 3\'-OH and 5\'-phosphate ends of adjacent fragments on the lagging strand.', source: 'locomotive-original', year: null },
    { id: 'bio-gen-q7', subject: 'Biology', topic: 'Genetics', difficulty: 'easy', stem: 'How many chromosomes are found in a normal human somatic cell?', options: ['A) 23', 'B) 44', 'C) 46', 'D) 48', 'E) 92'], correct_answer: 2, explanation: 'Human somatic cells are diploid (2n) and contain 46 chromosomes: 22 pairs of autosomes and 1 pair of sex chromosomes.', source: 'official-imat', year: 2021 },
    { id: 'bio-gen-q8', subject: 'Biology', topic: 'Genetics', difficulty: 'hard', stem: 'Which of the following best describes epigenetic inheritance?', options: ['A) Changes in the DNA sequence that are passed to offspring', 'B) Inheritance of traits through mitochondrial DNA only', 'C) Heritable changes in gene expression without changes to the DNA sequence', 'D) Inheritance of acquired characteristics as proposed by Lamarck', 'E) Horizontal gene transfer between organisms'], correct_answer: 2, explanation: 'Epigenetic inheritance involves heritable changes in gene expression (such as DNA methylation or histone modification) that do not involve changes to the underlying DNA sequence.', source: 'locomotive-original', year: null },

    // ===== BIOLOGY - Cell Biology =====
    { id: 'bio-cell-q1', subject: 'Biology', topic: 'Cell Biology', difficulty: 'medium', stem: 'Which organelle is responsible for producing ATP through oxidative phosphorylation?', options: ['A) Nucleus', 'B) Golgi apparatus', 'C) Endoplasmic reticulum', 'D) Mitochondria', 'E) Lysosome'], correct_answer: 3, explanation: 'Mitochondria are the powerhouses of the cell, producing ATP through oxidative phosphorylation in the inner mitochondrial membrane.', source: 'locomotive-original', year: null },
    { id: 'bio-cell-q2', subject: 'Biology', topic: 'Cell Biology', difficulty: 'easy', stem: 'Which of the following is NOT a function of the cell membrane?', options: ['A) Selective permeability', 'B) Cell signaling', 'C) DNA replication', 'D) Cell adhesion', 'E) Transport of molecules'], correct_answer: 2, explanation: 'DNA replication occurs in the nucleus, not at the cell membrane. The membrane is responsible for selective permeability, signaling, adhesion, and molecular transport.', source: 'official-imat', year: 2023 },
    { id: 'bio-cell-q3', subject: 'Biology', topic: 'Cell Biology', difficulty: 'medium', stem: 'During which phase of mitosis do chromosomes align at the cell\'s equator?', options: ['A) Prophase', 'B) Prometaphase', 'C) Metaphase', 'D) Anaphase', 'E) Telophase'], correct_answer: 2, explanation: 'During metaphase, chromosomes align at the metaphase plate (cell equator) before being separated in anaphase.', source: 'italian-medical', year: null },
    { id: 'bio-cell-q4', subject: 'Biology', topic: 'Cell Biology', difficulty: 'hard', stem: 'Which of the following correctly describes the fluid mosaic model of the cell membrane?', options: ['A) A rigid bilayer of phospholipids with embedded proteins', 'B) A fluid bilayer of phospholipids with laterally moving proteins', 'C) A single layer of phospholipids with fixed proteins', 'D) A triple layer of phospholipids with no proteins', 'E) A bilayer of proteins with embedded phospholipids'], correct_answer: 1, explanation: 'The fluid mosaic model describes the cell membrane as a fluid phospholipid bilayer with various proteins that can move laterally within the membrane.', source: 'official-imat', year: 2022 },
    { id: 'bio-cell-q5', subject: 'Biology', topic: 'Cell Biology', difficulty: 'medium', stem: 'What is the main function of the rough endoplasmic reticulum?', options: ['A) Lipid synthesis', 'B) Protein synthesis and processing', 'C) ATP production', 'D) DNA replication', 'E) Waste digestion'], correct_answer: 1, explanation: 'The rough ER is studded with ribosomes and is responsible for the synthesis and initial processing of proteins destined for secretion or membrane insertion.', source: 'locomotive-original', year: null },
    { id: 'bio-cell-q6', subject: 'Biology', topic: 'Cell Biology', difficulty: 'easy', stem: 'Which cellular structure contains the genetic material in eukaryotic cells?', options: ['A) Ribosome', 'B) Mitochondria', 'C) Nucleus', 'D) Golgi apparatus', 'E) Lysosome'], correct_answer: 2, explanation: 'The nucleus contains the cell\'s DNA organized into chromosomes and is the control center of the eukaryotic cell.', source: 'locomotive-original', year: null },
    { id: 'bio-cell-q7', subject: 'Biology', topic: 'Cell Biology', difficulty: 'hard', stem: 'Which of the following processes does NOT require ATP?', options: ['A) Active transport', 'B) Osmosis', 'C) Endocytosis', 'D) Muscle contraction', 'E) Sodium-potassium pump'], correct_answer: 1, explanation: 'Osmosis is a passive process where water moves across a semipermeable membrane from low to high solute concentration, without requiring energy input.', source: 'official-imat', year: 2024 },

    // ===== BIOLOGY - Anatomy =====
    { id: 'bio-anat-q1', subject: 'Biology', topic: 'Anatomy', difficulty: 'medium', stem: 'Which chamber of the heart pumps oxygenated blood to the body?', options: ['A) Right atrium', 'B) Right ventricle', 'C) Left atrium', 'D) Left ventricle', 'E) Superior vena cava'], correct_answer: 3, explanation: 'The left ventricle pumps oxygenated blood through the aorta to the systemic circulation, supplying oxygen to all body tissues.', source: 'official-imat', year: 2023 },
    { id: 'bio-anat-q2', subject: 'Biology', topic: 'Anatomy', difficulty: 'easy', stem: 'Which organ is primarily responsible for filtering blood and producing urine?', options: ['A) Liver', 'B) Kidney', 'C) Spleen', 'D) Pancreas', 'E) Gallbladder'], correct_answer: 1, explanation: 'The kidneys filter blood, remove waste products, and regulate fluid balance by producing urine.', source: 'locomotive-original', year: null },
    { id: 'bio-anat-q3', subject: 'Biology', topic: 'Anatomy', difficulty: 'hard', stem: 'The sinoatrial (SA) node is located in which part of the heart?', options: ['A) Left atrium', 'B) Right atrium', 'C) Left ventricle', 'D) Right ventricle', 'E) Interventricular septum'], correct_answer: 1, explanation: 'The SA node, the heart\'s natural pacemaker, is located in the wall of the right atrium near the superior vena cava opening.', source: 'italian-medical', year: null },
    { id: 'bio-anat-q4', subject: 'Biology', topic: 'Anatomy', difficulty: 'medium', stem: 'Gas exchange in the lungs occurs primarily in which structure?', options: ['A) Bronchi', 'B) Bronchioles', 'C) Trachea', 'D) Alveoli', 'E) Pleura'], correct_answer: 3, explanation: 'Alveoli are tiny air sacs in the lungs where gas exchange occurs — oxygen diffuses into the blood and carbon dioxide diffuses out.', source: 'official-imat', year: 2021 },

    // ===== CHEMISTRY - General =====
    { id: 'chem-gen-q1', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'easy', stem: 'What is the pH of a neutral solution at 25°C?', options: ['A) 0', 'B) 5', 'C) 7', 'D) 10', 'E) 14'], correct_answer: 2, explanation: 'At 25°C, a neutral solution has equal concentrations of H⁺ and OH⁻ ions, resulting in a pH of 7.', source: 'italian-medical', year: null },
    { id: 'chem-gen-q2', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'medium', stem: 'What is the electron configuration of a sodium atom (Na, Z=11)?', options: ['A) 1s² 2s² 2p⁶ 3s¹', 'B) 1s² 2s² 2p⁶ 3p¹', 'C) 1s² 2s² 2p⁷', 'D) 1s² 2s² 2p⁶ 3s²', 'E) 1s² 2s² 2p⁵ 3s²'], correct_answer: 0, explanation: 'Sodium has 11 electrons. Following the aufbau principle: 1s²(2) 2s²(4) 2p⁶(10) 3s¹(11).', source: 'official-imat', year: 2023 },
    { id: 'chem-gen-q3', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'hard', stem: 'Which of the following solutions acts as a buffer?', options: ['A) HCl and NaCl', 'B) CH₃COOH and CH₃COONa', 'C) NaOH and NaCl', 'D) H₂SO₄ and Na₂SO₄', 'E) HNO₃ and NaNO₃'], correct_answer: 1, explanation: 'A buffer consists of a weak acid and its conjugate base (or weak base and conjugate acid). Acetic acid (CH₃COOH) and sodium acetate (CH₃COONa) form a classic buffer system.', source: 'official-imat', year: 2022 },
    { id: 'chem-gen-q4', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'medium', stem: 'How many moles of water are produced when 2 moles of hydrogen react completely with 1 mole of oxygen?', options: ['A) 1 mole', 'B) 2 moles', 'C) 3 moles', 'D) 4 moles', 'E) 0.5 moles'], correct_answer: 1, explanation: '2H₂ + O₂ → 2H₂O. Two moles of hydrogen react with one mole of oxygen to produce two moles of water.', source: 'locomotive-original', year: null },
    { id: 'chem-gen-q5', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'easy', stem: 'Which of the following is a noble gas?', options: ['A) Nitrogen', 'B) Oxygen', 'C) Chlorine', 'D) Neon', 'E) Hydrogen'], correct_answer: 3, explanation: 'Neon (Ne) is a noble gas in Group 18 of the periodic table, characterized by a full outer electron shell and very low reactivity.', source: 'locomotive-original', year: null },
    { id: 'chem-gen-q6', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'hard', stem: 'What is the oxidation state of manganese in KMnO₄?', options: ['A) +2', 'B) +4', 'C) +5', 'D) +7', 'E) +3'], correct_answer: 3, explanation: 'In KMnO₄: K is +1, each O is -2. So +1 + Mn + 4(-2) = 0, giving Mn = +7.', source: 'official-imat', year: 2024 },
    { id: 'chem-gen-q7', subject: 'Chemistry', topic: 'General Chemistry', difficulty: 'medium', stem: 'Which type of bond is formed between sodium and chlorine in NaCl?', options: ['A) Covalent bond', 'B) Ionic bond', 'C) Metallic bond', 'D) Hydrogen bond', 'E) Van der Waals force'], correct_answer: 1, explanation: 'NaCl is formed by an ionic bond where sodium transfers an electron to chlorine, creating Na⁺ and Cl⁻ ions held together by electrostatic attraction.', source: 'locomotive-original', year: null },

    // ===== CHEMISTRY - Organic =====
    { id: 'chem-org-q1', subject: 'Chemistry', topic: 'Organic Chemistry', difficulty: 'hard', stem: 'What is the IUPAC name for the compound CH₃CH₂CH(OH)CH₃?', options: ['A) 1-Butanol', 'B) 2-Butanol', 'C) 2-Methylpropanol', 'D) Diethyl ether', 'E) Butanone'], correct_answer: 1, explanation: 'The hydroxyl group (-OH) is attached to the second carbon of a four-carbon chain, making it 2-butanol (butan-2-ol).', source: 'official-imat', year: 2022 },
    { id: 'chem-org-q2', subject: 'Chemistry', topic: 'Organic Chemistry', difficulty: 'medium', stem: 'Which functional group is present in aldehydes?', options: ['A) -OH', 'B) -COOH', 'C) -CHO', 'D) -NH₂', 'E) -CO-'], correct_answer: 2, explanation: 'Aldehydes contain the -CHO functional group, where a carbonyl group (C=O) is bonded to at least one hydrogen atom.', source: 'locomotive-original', year: null },
    { id: 'chem-org-q3', subject: 'Chemistry', topic: 'Organic Chemistry', difficulty: 'easy', stem: 'What is the general formula for alkanes?', options: ['A) CₙH₂ₙ', 'B) CₙH₂ₙ₊₂', 'C) CₙH₂ₙ₋₂', 'D) CₙHₙ', 'E) CₙH₂ₙ₊₁'], correct_answer: 1, explanation: 'Alkanes are saturated hydrocarbons with the general formula CₙH₂ₙ₊₂, where all carbon-carbon bonds are single bonds.', source: 'official-imat', year: 2021 },
    { id: 'chem-org-q4', subject: 'Chemistry', topic: 'Organic Chemistry', difficulty: 'hard', stem: 'Which of the following amino acids has a nonpolar, hydrophobic side chain?', options: ['A) Serine', 'B) Glutamic acid', 'C) Lysine', 'D) Leucine', 'E) Aspartic acid'], correct_answer: 3, explanation: 'Leucine has an isobutyl side chain which is nonpolar and hydrophobic, making it typically found in the interior of proteins.', source: 'italian-medical', year: null },
    { id: 'chem-org-q5', subject: 'Chemistry', topic: 'Organic Chemistry', difficulty: 'medium', stem: 'What type of reaction occurs when an ester is formed from a carboxylic acid and an alcohol?', options: ['A) Hydrolysis', 'B) Oxidation', 'C) Condensation (esterification)', 'D) Reduction', 'E) Substitution'], correct_answer: 2, explanation: 'Esterification is a condensation reaction where a carboxylic acid reacts with an alcohol to form an ester and water, typically catalyzed by an acid.', source: 'locomotive-original', year: null },

    // ===== PHYSICS - Mechanics =====
    { id: 'phys-mech-q1', subject: 'Physics', topic: 'Mechanics', difficulty: 'easy', stem: 'A ball is thrown vertically upward with an initial velocity of 20 m/s. Ignoring air resistance (g = 10 m/s²), what is the maximum height reached?', options: ['A) 10 m', 'B) 20 m', 'C) 30 m', 'D) 40 m', 'E) 50 m'], correct_answer: 1, explanation: 'Using v² = u² - 2gh, at max height v = 0: 0 = 400 - 20h, so h = 20 m.', source: 'locomotive-original', year: null },
    { id: 'phys-mech-q2', subject: 'Physics', topic: 'Mechanics', difficulty: 'medium', stem: 'Two forces of 3N and 4N act on an object at right angles to each other. What is the resultant force?', options: ['A) 1 N', 'B) 5 N', 'C) 7 N', 'D) 12 N', 'E) 25 N'], correct_answer: 1, explanation: 'Using the Pythagorean theorem: R = √(3² + 4²) = √(9 + 16) = √25 = 5 N.', source: 'locomotive-original', year: null },
    { id: 'phys-mech-q3', subject: 'Physics', topic: 'Mechanics', difficulty: 'medium', stem: 'A 5 kg object accelerates at 3 m/s². What is the net force acting on it?', options: ['A) 1.67 N', 'B) 8 N', 'C) 15 N', 'D) 0.6 N', 'E) 45 N'], correct_answer: 2, explanation: 'Using Newton\'s second law: F = ma = 5 × 3 = 15 N.', source: 'official-imat', year: 2023 },
    { id: 'phys-mech-q4', subject: 'Physics', topic: 'Mechanics', difficulty: 'hard', stem: 'A 2 kg ball is dropped from a height of 45 m. What is its velocity just before hitting the ground? (g = 10 m/s²)', options: ['A) 10 m/s', 'B) 20 m/s', 'C) 30 m/s', 'D) 45 m/s', 'E) 90 m/s'], correct_answer: 2, explanation: 'Using v² = u² + 2gh: v² = 0 + 2(10)(45) = 900, so v = 30 m/s.', source: 'official-imat', year: 2022 },
    { id: 'phys-mech-q5', subject: 'Physics', topic: 'Mechanics', difficulty: 'easy', stem: 'What is the SI unit of force?', options: ['A) Joule', 'B) Watt', 'C) Newton', 'D) Pascal', 'E) Hertz'], correct_answer: 2, explanation: 'The Newton (N) is the SI unit of force, defined as the force needed to accelerate 1 kg by 1 m/s².', source: 'locomotive-original', year: null },
    { id: 'phys-mech-q6', subject: 'Physics', topic: 'Mechanics', difficulty: 'medium', stem: 'A car travels 100 km in 2 hours, then 150 km in 3 hours. What is the average speed?', options: ['A) 40 km/h', 'B) 45 km/h', 'C) 50 km/h', 'D) 55 km/h', 'E) 60 km/h'], correct_answer: 2, explanation: 'Average speed = total distance / total time = (100 + 150) / (2 + 3) = 250 / 5 = 50 km/h.', source: 'locomotive-original', year: null },

    // ===== PHYSICS - Thermodynamics =====
    { id: 'phys-therm-q1', subject: 'Physics', topic: 'Thermodynamics', difficulty: 'easy', stem: 'What is the boiling point of water at standard atmospheric pressure in Kelvin?', options: ['A) 100 K', 'B) 212 K', 'C) 273 K', 'D) 373 K', 'E) 473 K'], correct_answer: 3, explanation: 'Water boils at 100°C at standard pressure. Converting to Kelvin: 100 + 273 = 373 K.', source: 'locomotive-original', year: null },
    { id: 'phys-therm-q2', subject: 'Physics', topic: 'Thermodynamics', difficulty: 'medium', stem: 'Which law of thermodynamics states that energy cannot be created or destroyed?', options: ['A) Zeroth law', 'B) First law', 'C) Second law', 'D) Third law', 'E) Boyle\'s law'], correct_answer: 1, explanation: 'The first law of thermodynamics (conservation of energy) states that energy cannot be created or destroyed, only transformed from one form to another.', source: 'official-imat', year: 2023 },
    { id: 'phys-therm-q3', subject: 'Physics', topic: 'Thermodynamics', difficulty: 'hard', stem: 'An ideal gas undergoes an isothermal expansion, doubling its volume. What happens to the pressure?', options: ['A) Doubles', 'B) Halves', 'C) Remains the same', 'D) Quadruples', 'E) Quarters'], correct_answer: 1, explanation: 'For an isothermal process with an ideal gas, PV = constant (Boyle\'s law). If volume doubles, pressure must halve.', source: 'official-imat', year: 2024 },
    { id: 'phys-therm-q4', subject: 'Physics', topic: 'Thermodynamics', difficulty: 'medium', stem: 'How much heat is needed to raise the temperature of 2 kg of water by 5°C? (c = 4200 J/kg°C)', options: ['A) 4,200 J', 'B) 10,500 J', 'C) 21,000 J', 'D) 42,000 J', 'E) 84,000 J'], correct_answer: 3, explanation: 'Q = mcΔT = 2 × 4200 × 5 = 42,000 J.', source: 'locomotive-original', year: null },

    // ===== MATHEMATICS - Algebra =====
    { id: 'math-alg-q1', subject: 'Mathematics', topic: 'Algebra', difficulty: 'easy', stem: 'What is the value of x in the equation 3x + 7 = 22?', options: ['A) 3', 'B) 4', 'C) 5', 'D) 6', 'E) 7'], correct_answer: 2, explanation: '3x + 7 = 22 → 3x = 15 → x = 5.', source: 'locomotive-original', year: null },
    { id: 'math-alg-q2', subject: 'Mathematics', topic: 'Algebra', difficulty: 'medium', stem: 'What are the solutions of x² - 5x + 6 = 0?', options: ['A) x = 1, x = 6', 'B) x = 2, x = 3', 'C) x = -2, x = -3', 'D) x = -1, x = -6', 'E) x = 1, x = 5'], correct_answer: 1, explanation: 'Factoring: (x - 2)(x - 3) = 0, so x = 2 or x = 3.', source: 'official-imat', year: 2023 },
    { id: 'math-alg-q3', subject: 'Mathematics', topic: 'Algebra', difficulty: 'hard', stem: 'If log₂(x) + log₂(x - 2) = 3, what is the value of x?', options: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 8'], correct_answer: 2, explanation: 'log₂(x(x-2)) = 3 → x(x-2) = 8 → x² - 2x - 8 = 0 → (x-4)(x+2) = 0. Since x > 2, x = 4.', source: 'official-imat', year: 2022 },
    { id: 'math-alg-q4', subject: 'Mathematics', topic: 'Algebra', difficulty: 'medium', stem: 'What is the sum of the arithmetic series 2 + 5 + 8 + 11 + ... + 29?', options: ['A) 145', 'B) 155', 'C) 160', 'D) 165', 'E) 170'], correct_answer: 1, explanation: 'a = 2, d = 3, last term = 29. Number of terms: (29-2)/3 + 1 = 10. Sum = 10/2 × (2 + 29) = 155.', source: 'locomotive-original', year: null },

    // ===== MATHEMATICS - Calculus =====
    { id: 'math-calc-q1', subject: 'Mathematics', topic: 'Calculus', difficulty: 'medium', stem: 'What is the derivative of f(x) = 3x² + 2x - 5?', options: ['A) 6x + 2', 'B) 6x - 2', 'C) 3x + 2', 'D) 6x² + 2', 'E) 6x'], correct_answer: 0, explanation: 'Using the power rule: d/dx(3x²) = 6x, d/dx(2x) = 2, d/dx(-5) = 0. So f\'(x) = 6x + 2.', source: 'locomotive-original', year: null },
    { id: 'math-calc-q2', subject: 'Mathematics', topic: 'Calculus', difficulty: 'easy', stem: 'What is ∫2x dx?', options: ['A) x²', 'B) x² + C', 'C) 2x² + C', 'D) x + C', 'E) 2x'], correct_answer: 1, explanation: '∫2x dx = 2 · x²/2 + C = x² + C.', source: 'locomotive-original', year: null },
    { id: 'math-calc-q3', subject: 'Mathematics', topic: 'Calculus', difficulty: 'hard', stem: 'What is the derivative of f(x) = sin(x²)?', options: ['A) cos(x²)', 'B) 2x·cos(x²)', 'C) x²·cos(x²)', 'D) 2·sin(x)·cos(x)', 'E) -cos(x²)'], correct_answer: 1, explanation: 'Using the chain rule: f\'(x) = cos(x²) · d/dx(x²) = 2x·cos(x²).', source: 'official-imat', year: 2024 },
    { id: 'math-calc-q4', subject: 'Mathematics', topic: 'Calculus', difficulty: 'medium', stem: 'What is the limit of (sin x)/x as x approaches 0?', options: ['A) 0', 'B) 1', 'C) ∞', 'D) -1', 'E) undefined'], correct_answer: 1, explanation: 'This is a fundamental limit in calculus: lim(x→0) sin(x)/x = 1, which can be proven using the squeeze theorem.', source: 'official-imat', year: 2023 },

    // ===== LOGIC =====
    { id: 'logic-q1', subject: 'Logic', topic: 'Critical Thinking', difficulty: 'medium', stem: 'If all doctors are scientists, and some scientists are musicians, which of the following must be true?', options: ['A) All doctors are musicians', 'B) Some doctors are musicians', 'C) No doctors are musicians', 'D) Some scientists are doctors', 'E) All musicians are scientists'], correct_answer: 3, explanation: 'Since all doctors are scientists, the set of doctors is a subset of scientists. Therefore, some scientists are indeed doctors.', source: 'italian-medical', year: null },
    { id: 'logic-q2', subject: 'Logic', topic: 'Critical Thinking', difficulty: 'easy', stem: 'If it is raining, then the ground is wet. The ground is not wet. What can we conclude?', options: ['A) It is raining', 'B) It is not raining', 'C) The ground might be wet', 'D) We cannot conclude anything', 'E) It will rain later'], correct_answer: 1, explanation: 'This is modus tollens: If P → Q, and ¬Q, then ¬P. Since the ground is not wet, it is not raining.', source: 'locomotive-original', year: null },
    { id: 'logic-q3', subject: 'Logic', topic: 'Critical Thinking', difficulty: 'hard', stem: 'In a room of 30 people, what is the minimum number that must share a birth month?', options: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 6'], correct_answer: 1, explanation: 'By the pigeonhole principle, with 30 people and 12 months, at least ⌈30/12⌉ = 3 people must share a birth month.', source: 'official-imat', year: 2023 },
    { id: 'logic-q4', subject: 'Logic', topic: 'Problem Solving', difficulty: 'medium', stem: 'What is the next number in the sequence: 2, 6, 18, 54, ...?', options: ['A) 72', 'B) 108', 'C) 162', 'D) 216', 'E) 148'], correct_answer: 2, explanation: 'This is a geometric sequence with a common ratio of 3. Each term is multiplied by 3: 54 × 3 = 162.', source: 'locomotive-original', year: null },
    { id: 'logic-q5', subject: 'Logic', topic: 'Problem Solving', difficulty: 'easy', stem: 'If you rearrange the letters "CIFAIPC" you would have the name of a(n):', options: ['A) City', 'B) Animal', 'C) Ocean', 'D) Country', 'E) River'], correct_answer: 2, explanation: 'Rearranging "CIFAIPC" gives "PACIFIC", which is the name of an ocean.', source: 'locomotive-original', year: null },
    { id: 'logic-q6', subject: 'Logic', topic: 'Critical Thinking', difficulty: 'medium', stem: 'A statement says: "This statement is false." This is an example of:', options: ['A) A tautology', 'B) A paradox', 'C) An axiom', 'D) A syllogism', 'E) A hypothesis'], correct_answer: 1, explanation: 'This is the liar\'s paradox — if the statement is true, then it must be false, but if it is false, then it must be true. It creates a logical contradiction.', source: 'locomotive-original', year: null },

    // ===== GENERAL KNOWLEDGE =====
    { id: 'gk-q1', subject: 'General Knowledge', topic: 'History of Medicine', difficulty: 'easy', stem: 'Who is credited with the discovery of penicillin?', options: ['A) Louis Pasteur', 'B) Robert Koch', 'C) Alexander Fleming', 'D) Edward Jenner', 'E) Joseph Lister'], correct_answer: 2, explanation: 'Alexander Fleming discovered penicillin in 1928 when he noticed that mold (Penicillium notatum) inhibited bacterial growth on a culture plate.', source: 'official-imat', year: 2021 },
    { id: 'gk-q2', subject: 'General Knowledge', topic: 'History of Medicine', difficulty: 'medium', stem: 'The Hippocratic Oath is traditionally attributed to which ancient Greek physician?', options: ['A) Galen', 'B) Hippocrates', 'C) Aristotle', 'D) Herophilus', 'E) Asclepius'], correct_answer: 1, explanation: 'The Hippocratic Oath, a foundation of medical ethics, is attributed to Hippocrates of Kos (c. 460–370 BC), often called the "Father of Medicine."', source: 'official-imat', year: 2023 },
    { id: 'gk-q3', subject: 'General Knowledge', topic: 'Scientific Literacy', difficulty: 'medium', stem: 'What does the term "double-blind" refer to in a clinical trial?', options: ['A) Two groups of patients are used', 'B) Neither the researcher nor the participant knows who receives treatment', 'C) The trial is conducted in two phases', 'D) Two different drugs are compared', 'E) The results are checked twice'], correct_answer: 1, explanation: 'In a double-blind trial, neither the participants nor the researchers know who is receiving the treatment vs. placebo, reducing bias.', source: 'locomotive-original', year: null },
    { id: 'gk-q4', subject: 'General Knowledge', topic: 'History of Medicine', difficulty: 'hard', stem: 'Who developed the first successful smallpox vaccine?', options: ['A) Louis Pasteur', 'B) Robert Koch', 'C) Alexander Fleming', 'D) Edward Jenner', 'E) Jonas Salk'], correct_answer: 3, explanation: 'Edward Jenner developed the first successful smallpox vaccine in 1796, using cowpox virus to provide immunity against smallpox.', source: 'official-imat', year: 2022 },
    { id: 'gk-q5', subject: 'General Knowledge', topic: 'Scientific Literacy', difficulty: 'easy', stem: 'What does DNA stand for?', options: ['A) Deoxyribonucleic acid', 'B) Dinitrogen acid', 'C) Deoxynucleotide acid', 'D) Dynamic nucleic acid', 'E) Dual nucleotide array'], correct_answer: 0, explanation: 'DNA stands for deoxyribonucleic acid, the molecule that carries genetic instructions for development and functioning of living organisms.', source: 'locomotive-original', year: null },

    // ===== READING COMPREHENSION =====
    { id: 'rc-q1', subject: 'Reading Comprehension', topic: 'Scientific Passages', difficulty: 'medium', stem: 'A study found that mice exposed to bright light at night had higher rates of tumor growth compared to controls. The researchers concluded that disrupted circadian rhythms may promote cancer. Which of the following, if true, would most weaken this conclusion?', options: ['A) The bright light caused stress in the mice, which independently promotes tumor growth', 'B) Similar results were found in other animal models', 'C) The study was conducted over a 12-month period', 'D) The control group was kept in complete darkness', 'E) The tumors were of the same type in both groups'], correct_answer: 0, explanation: 'If stress from bright light, rather than circadian disruption, caused the tumor growth, then the conclusion about circadian rhythms is weakened by an alternative explanation.', source: 'official-imat', year: 2023 },
    { id: 'rc-q2', subject: 'Reading Comprehension', topic: 'Text Analysis', difficulty: 'easy', stem: '"The new treatment showed a 40% reduction in symptoms compared to placebo. However, 15% of patients reported significant side effects." What is the main idea of this passage?', options: ['A) The treatment is completely safe', 'B) The treatment is effective but has notable side effects', 'C) The placebo was more effective', 'D) Side effects are more important than efficacy', 'E) 40% of patients recovered completely'], correct_answer: 1, explanation: 'The passage presents both the benefit (40% symptom reduction) and the drawback (15% with side effects), indicating the treatment is effective but has notable risks.', source: 'locomotive-original', year: null },
    { id: 'rc-q3', subject: 'Reading Comprehension', topic: 'Scientific Passages', difficulty: 'hard', stem: 'A researcher observes that countries with higher chocolate consumption per capita also have more Nobel Prize winners. The researcher suggests that chocolate improves cognitive function. This reasoning is flawed because:', options: ['A) The sample size is too small', 'B) Correlation does not imply causation', 'C) Nobel Prizes are not a valid measure of intelligence', 'D) Not all chocolate is the same', 'E) The data was self-reported'], correct_answer: 1, explanation: 'This is an example of the correlation-causation fallacy. The association between chocolate consumption and Nobel Prizes could be due to confounding variables (e.g., wealth, education systems) rather than a causal link.', source: 'official-imat', year: 2024 },
    { id: 'rc-q4', subject: 'Reading Comprehension', topic: 'Text Analysis', difficulty: 'medium', stem: '"While antibiotics have saved millions of lives since their discovery, their overuse has led to the emergence of resistant bacteria, posing one of the greatest threats to public health today." The author\'s tone is best described as:', options: ['A) Optimistic', 'B) Indifferent', 'C) Balanced and cautionary', 'D) Dismissive', 'E) Alarmed'], correct_answer: 2, explanation: 'The author acknowledges the benefits of antibiotics while warning about the dangers of overuse, showing a balanced yet cautionary perspective.', source: 'locomotive-original', year: null },
];

async function seedQuestions() {
    console.log('🌱 Seeding expanded question bank...\n');
    console.log(`📊 Total questions to insert: ${questions.length}\n`);

    // Format for DB
    const questionsForDb = questions.map(q => ({
        ...q,
        options: JSON.stringify(q.options),
    }));

    // Insert in batches of 20
    const batchSize = 20;
    let inserted = 0;
    for (let i = 0; i < questionsForDb.length; i += batchSize) {
        const batch = questionsForDb.slice(i, i + batchSize);
        const { error } = await supabase.from('questions').upsert(batch, { onConflict: 'id' });
        if (error) {
            console.error(`  ❌ Error at batch ${i / batchSize + 1}:`, error.message);
            return;
        }
        inserted += batch.length;
        console.log(`  ✅ Inserted ${inserted}/${questionsForDb.length}`);
    }

    // Print summary by subject
    const subjects: Record<string, number> = {};
    questions.forEach(q => { subjects[q.subject] = (subjects[q.subject] || 0) + 1; });
    console.log('\n📋 Questions by subject:');
    Object.entries(subjects).sort(([, a], [, b]) => b - a).forEach(([s, c]) => {
        console.log(`   ${s}: ${c}`);
    });

    console.log('\n🎉 Done!');
}

seedQuestions().catch(console.error);
